# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpewEPfG_8IHBfgVNAIIUUzFuXj7RYSx
"""

alumnu = {
    "nombre": input("ingrese su nombre:"),
    "telefono": int(input("ingrese su telefono:")),
    "email":input("ingrese su email"),
    "edad": int(input("ingrese su edad:"));
}
while True:
print("***===MENU===***")
print("1-ver alumno")
print("2-editar algun campo")
print("3-salir")

opcion=int(input("ingrese opcion:"))
if opcion==1:
    print(alumno)
elif opcion==2:

    campo=input("que campo desea editar?")
    nuevo=input("ingrese el datos nuevo:")
    alumno[campo]=nuevo

elif opcion==3:
        print("saliendo")

break: